### ISSUE TITLE
GMU Console breaks due to GameMaker updated to 64-bit.

### ISSUE THREAD

**Issue by ItsEntDev** [TML233/UndertaleEngine#106]
Whenever I start the Demo project I get this fatal error:

___________________________________________
############################################################################################
ERROR in
action number 1
of Other Event: Game Start
for object world:

Error defining an external function.
 at gml_Script_Console_Init (line 8) -               global._gmu_console_function_init=external_define(dll,"Init",call,ty_real,0);
############################################################################################
gml_Script_Console_Init (line 8)
gml_Object_world_Other_2 (line 3) - Console_Init();

and I believe it might be todo with a missing thing known as gmu_console. Where could I find that (if I am correct) and how would I go about installing it?

**Comment by ItsEntDev** [comment]
Also, all the documentation is down

**Comment by TML233** [comment]
The example project is written in GMS 2.2 and haven't been fixed since then. Previous updates of GMS 2.3 have broken several things of this old project. You might need to apply the fixes of the master branch to the example project manually.

If you need more information, you can join the [discord server](https://discord.gg/njvUdff)

**Comment by Ceyase** [comment]
#117 fixed this

**Comment by TML233** [comment]
GameMaker's 64-bit runner no-longer supports 32-bit DLLs.
And latest GameMaker has the console built-in.
We are going to remove the old console plugin from the project.

**Comment by TML233** [comment]
#126 fixed this.
